version: '3'
services:
  consul:
    image: 'hashicorp/consul'
    ports:
      - 8500:8500
#  mysql:
#    image: 'mysql:8.0.32'
#    ports:
#      - 3306:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=demo_proto
#我的mysql是在本地的，所以这里注释掉
  redis:
    image: "redis:6.2"
    ports:
      - 6379:6379
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"

